<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace eluhr\analytics\core\models\base;

use Yii;

/**
 * This is the base-model class for table "app_dmstr_analytic_data".
 *
 * @property string $id
 * @property string $type
 * @property resource $data
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class AnalyticData extends \eluhr\analytics\core\models\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'app_analytic_data';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'type', 'data'], 'required'],
            [['data'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['id'], 'string', 'max' => 36],
            [['type'], 'string', 'max' => 128],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('analytics', 'ID'),
            'type' => Yii::t('analytics', 'Type'),
            'data' => Yii::t('analytics', 'Data'),
            'created_at' => Yii::t('analytics', 'Created At'),
            'updated_at' => Yii::t('analytics', 'Updated At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \eluhr\analytics\core\models\query\AnalyticDataQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \eluhr\analytics\core\models\query\AnalyticDataQuery(get_called_class());
    }


}
